kind: KongPluginInstallation
apiVersion: gateway-operator.konghq.com/v1alpha1
metadata:
  name: kong-ki-selfhost-router
spec:
  # git@gitlab.com:knowledge-integration/platform/kong-ki-selfhost-router.git
  image: docker.libsdev.k-int.com/knowledgeintegration/kong-ki-selfhost-router:latest

