apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
# Redis = Standalone, RedisCluster/RedisReplication for prod workloads
metadata:
  name: redis
spec:
  redisConfig:         # optional: extra redis.conf settings
    additionalRedisConfig: ""  # leave blank for defaults
  kubernetesConfig:
    image: redis:7.2.5           # or whatever version you prefer
    imagePullPolicy: IfNotPresent
  redisExporter:
    enabled: false               # disable metrics exporter
  # storage:
  #   volumeClaimTemplate:
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 1Gi
  # # Replication settings
  clusterSize: 1                  # 1 pod = standalone
  redisLeader: redis-standalone
