kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v1beta1
metadata:
  name: ki-selfhost-gw-config
spec:
  dataPlaneOptions:
    deployment:
      replicas: 1
      podTemplateSpec:
        spec:
          containers:
            - name: proxy
              image: kong/kong:3.9.1
              # image: kong/kong-gateway:3.11
    # plugins:
    #   - name: kong-ki-selfhost-router
    #     config:
    #       header_value: "WibbleDibbleDoo"
    #       config_url: "http://ki-selfhost-operator/_/config"
    pluginsToInstall:
      - name: kong-ki-selfhost-router
  controlPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
            - name: controller
              image: kong/kubernetes-ingress-controller:3.4
