apiVersion: apps/v1
kind: Deployment
metadata:
  name: ki-selfhost-operator
  labels:
    app.kubernetes.io/name: ki-selfhost-operator
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ki-selfhost-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: ki-selfhost-operator
    spec:
      containers:
        - name: ki-selfhost-operator
          image: docker.libsdev.k-int.com/knowledgeintegration/ki-selfhost-operator@sha256:da0e6b8f53602335bf9d10fc6b032ff7b41473383819f4458f56478656b1205b
          # image: docker.libsdev.k-int.com/knowledgeintegration/ki-selfhost-operator:native-next
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ki-selfhost-secrets
          env:
            # TODO: Add and Update for CNPG PG Deployment
            # - name: POD_NAME
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.name
            # - name: DATASOURCE_HOST
            #   valueFrom : { secretKeyRef : { name: postgres-pguser-cheetah, key: host } }
            # - name: DATASOURCE_PORT
            #   valueFrom : { secretKeyRef : { name: postgres-pguser-cheetah, key: port } }
            # - name: DATASOURCE_DB
            #   valueFrom : { secretKeyRef : { name: postgres-pguser-cheetah, key: dbname } }
            # - name: DATASOURCE_USERNAME
            #   valueFrom : { secretKeyRef : { name: postgres-pguser-cheetah, key: user } }
            # - name: DATASOURCE_PASSWORD
            #   valueFrom : { secretKeyRef : { name: postgres-pguser-cheetah, key: password } }
            # - name: DATASOURCE_URL
            #   value: "jdbc:postgresql://$(DATASOURCE_HOST):$(DATASOURCE_PORT)/$(DATASOURCE_DB)"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 768Mi
            limits:
              memory: 2Gi
      serviceAccountName: {{ include "ki-selfhost-operator.serviceAccountName" . }}
