apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-service-discoverer
  labels:
    {{- include "ki-selfhost-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: ki-selfhost-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: service-discoverer
  apiGroup: rbac.authorization.k8s.io
{{- end }}
