apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-discoverer
  labels:
    {{- include "ki-selfhost-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "configmaps", "secrets", "pods"]
    verbs: ["get", "watch", "list"]
{{- end }}
