apiVersion: gateway-operator.konghq.com/v1beta1
kind: DataPlane
metadata:
  name: ki-selfhost-dataplane
spec:
  deployment:
    replicas: 1
    podTemplateSpec:
      spec:
        containers:
          - name: proxy
            env:
              - name: KONG_PLUGINS
                value: bundled,tenant-router
            image: docker.libsdev.k-int.com/knowledgeintegration/kong-ki-selfhost-router:latest
