apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: ki-selfhost-gw-class
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
     group: gateway-operator.konghq.com
     kind: GatewayConfiguration
     name: kong-gateway-config
     namespace: {{ .Release.Namespace }}
