apiVersion: gateway-operator.konghq.com/v1beta1
kind: KongGateway
metadata:
  name: tenant-gateway
spec:
  deployment:
    podTemplate:
      spec:
        containers:
          - name: proxy
            image: docker.libsdev.k-int.com/knowledgeintegration/kong-ki-selfhost-router:latest
            env:
              - name: KONG_LOG_LEVEL
                value: debug
              - name: KONG_PLUGINS
                value: bundled,tenant-router
