# Default values for ki-selfhost-operator.

serviceAccount:
  name: ki-selfhost-operator-sa

kiSelfhostBootstrapToken: 12345

kishOperatorImage:
  ref: "docker.libsdev.k-int.com/knowledgeintegration/ki-selfhost-operator@sha256:c46d89fd714c976a7dc42a8db332a92d4638af0716f3bddf183354d227847d93"
