# Default values for ki-selfhost-operator.

serviceAccount:
  name: ki-selfhost-operator-sa

kiSelfhostBootstrapToken: 12345

kishOperatorImage:
  ref: "docker.libsdev.k-int.com/knowledgeintegration/ki-selfhost-operator@sha256:fc820d8e1f5a469331968a8447991595e71fd6f81a1936f4fd884b8a8b209525"
