# Default values for ki-selfhost-operator.

serviceAccount:
  name: ki-selfhost-operator-sa

kiSelfhostBootstrapToken: 12345

kishOperatorImage:
  ref: "docker.libsdev.k-int.com/knowledgeintegration/ki-selfhost-operator@sha256:0a38d4ac66a51faced05f22d35b7c6ab01f9b6d5d5a0900166f8758120213d7f"
