# myapp-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: selfhost-operator.k-int.com
spec:
  group: k-int.com
  names:
    kind: KISelfHostOperator
    listKind: KISelfHostOperatorList
    plural: KISelfHostedOperators
    singular: KISelfHostedOperator
  scope: Cluster-Scoped
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                image:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                replicas:
                  type: integer
