apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-check-crd"
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    spec:
      containers:
        - name: check-crd
          image: bitnami/kubectl:latest # Use a lightweight image with kubectl
          command: 
            - sh 
            - -c 
            - |
              if ! kubectl get crd postgresclusters.postgres-operator.crunchydata.com; then
                echo "Crunchydata PGO Not found"
                exit 1
              fi
      restartPolicy: Never
  backoffLimit: 1

