apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
stringData:
  QUIRE_BOOTSTRAP_TOKEN: {{ required "A valid configValue is required!" .Values.quireBootstrapToken | quote }}
  QUIRE_MGT_API: {{ .Values.managementAPI }}
  QUIRE_OPERATING_MODE: {{ .Values.quireOperatingMode }}
