apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
stringData:
  QUIRE_MGT_TOKEN: {{ required "A valid configValue is required!" .Values.quireManagementToken | quote }}
  QUIRE_MGT_API: {{ .Values.managementAPI }}
