apiVersion: v2
name: ki-selfhost-operator
description: A Helm chart the Knowledge Integration Self-Hosting Operator


# NON-HELM DEPENDENCIES
#
# K3D: k3d cluster create kong-dev \\n  --api-port 6550 \\n  -p "8080:80@loadbalancer" \\n  -p "8443:443@loadbalancer" \\n  --k3s-arg "--disable=traefik@server:0"
#
# CNPG - Cloud Native Postgres Operator
#
# https://cloudnative-pg.io/documentation/current/installation_upgrade/
#
#   kubectl apply --server-side -f \
#     https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.26/releases/cnpg-1.26.1.yaml
#
# Kong API Gateway Operator
#
# https://developer.konghq.com/operator/dataplanes/get-started/hybrid/install/
#
# kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
#
# helm repo add kong https://charts.konghq.com
#
# helm repo update kong
#
# PENDING helm show values kong/gateway-operator > values.yaml
#
# helm upgrade --install kgo kong/gateway-operator -n kong-system --create-namespace  \
#  --set image.tag=1.6.1 \
#  --set kubernetes-configuration-crds.enabled=true \
#  --set env.ENABLE_CONTROLLER_KONNECT=true
#
#

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.24

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"


dependencies:
  - name: eck-operator
    repository: https://helm.elastic.co
    condition: elasticSearchOperator.enabled
    version: 2.14.0

